import Foundation

enum RNHapticPatternResolver {
    static let patternNames: [String] = ["selection","soft","rigid","light","medium","heavy","success","error","warning","lightningStrikeQuick","lightningStrikeChain","lightningStrikeHeavy","coinCollectSingle","coinCollectMulti","coinCollectJackpot","swordSlashLight","swordSlashHeavy","arrowRelease","explosionSmall","explosionMassive","shieldBlock","criticalHit","comboHit3x","comboHit5x","footstepGrass","footstepMetal","engineStart","turboBoost","portalEnter","magicCharge","machineGun","cascade","elasticBounce","drums","achievementUnlocked","levelUp","starRating","badgeEarned","streakMilestone","perfectScore","rankPromotion","dailyGoalComplete","trophyUnlock","questComplete","highScore","masteryAchieved","correctAnswerBasic","correctAnswerSimple","correctAnswerStreak","correctAnswerPerfect","perfectLessonComplete","badgeUnlock","skillMastery","leaguePromotion","celebrationBurst","ascendingSuccess","correctAnswer","incorrectGentle","hintAvailable","progressCheckpoint","encouragementTap","skillUnlocked","lessonComplete","practiceReminder","knowledgeGained","feedbackPositive","wrongAnswerGentle","wrongAnswerStandard","nearMissAnswer","grammarError","hintActivation","hintReveal","timeCriticalWarning","partialCredit","tryAgainEncouragement","learningProgress","educationalFocusReminder","flashcardFlip","quizStart","xpGainSmall","xpGainLarge","xpGainBonus","xpGainDynamic","bonusPoints","powerUpCollected","lifeGained","challengeAccepted","timerTick","rewardUnlock","progressBarFill","progressBarFilling","progress25","progress50","progress75","dailyGoalCheckpoint","leagueAdvancement","crownGemCollection","powerUpActivation","challengeCompletion","lessonPathProgress","socialFeatureNotification","comboMultiplier","streakRiskWarning","streakLost","streakBuilding","streakMilestone5","streakMilestone7Days","streakMilestone10","streakMilestone25","streakMilestone30Days","streakMilestone100Days","doubleTapLike","messageSent","notificationPop","typingIndicator","commentPosted","pullToRefresh","swipeAction","toggleSwitch","pickerDetent","longPressActivation","tabSelection","navigationPush","navigationPop","modalPresent","modalDismiss","keyboardTap","sliderStep","sliderTick","buttonPress","selectionTick","segmentChange","zoomBoundary","dragAndDrop","formSubmit","inputError","loadingComplete","appIconTap","scrollBounce","pageFlip","photoCapture","shareAction","downloadComplete","refreshData","gestureRecognized","pageTurn","bookPageTurn","softTick","customPop","contextualMenu","sliderValueChange","pop","magicSparkle","waterDrop","specialEarthquake","laserBeam","typewriter","heartbeat","electricSpark","rubberBand","buildUp","boing","inflate","oscillate","breathingGuide","calmPulse","meditationBell","relaxationWave","zenNotification","timeWarning30s","timeWarning10s","heartBeats","timerComplete","taskCheck","focusStart","breakReminder","productivityFocusReminder","paymentSuccess","paymentProcessing","transactionAlert","receiptSaved","excitementBuild","disappointment","surprise","joy","anticipation","fireBurst","iceShard","earthquakeRumble","windTornado","thunderStorm","meteorImpact","intenseEarthquake","intenseTornado","plasmaCharge","gravityWell","photonBlast","quantumShift","rocketLaunch","warpDrive","laserCannon","alienTeleport","spaceExplosion","ultimatePower","dragonRoar","titanSmash","dimensionalRift","volcanicEruption","titanStomp","phoenixRebirth","divineIntervention","megaBoost","starPower","berserkerRage","divineShield","invincibilityActivation","timeFreeze","ultraCombo","nuclearCharge","starRating1","starRating3","starRating5","socialNotification","pencilWrite","eraserUse"]

    static func option(named name: String, options: [String: Any]?) -> HapticOption? {
        switch name {
        case "selection": return .selection
        case "soft": return .soft
        case "rigid": return .rigid
        case "light": return .light
        case "medium": return .medium
        case "heavy": return .heavy
        case "success": return .success
        case "error": return .error
        case "warning": return .warning
        case "lightningStrikeQuick": return .lightningStrikeQuick(duration: double(options, "duration", 0.3))
        case "lightningStrikeChain": return .lightningStrikeChain(duration: double(options, "duration", 1.2))
        case "lightningStrikeHeavy": return .lightningStrikeHeavy(duration: double(options, "duration", 1.5))
        case "coinCollectSingle": return .coinCollectSingle(duration: double(options, "duration", 0.15))
        case "coinCollectMulti": return .coinCollectMulti(duration: double(options, "duration", 0.8))
        case "coinCollectJackpot": return .coinCollectJackpot(duration: double(options, "duration", 2.0))
        case "swordSlashLight": return .swordSlashLight(duration: double(options, "duration", 0.25))
        case "swordSlashHeavy": return .swordSlashHeavy(duration: double(options, "duration", 0.6))
        case "arrowRelease": return .arrowRelease(duration: double(options, "duration", 0.5))
        case "explosionSmall": return .explosionSmall(duration: double(options, "duration", 0.4))
        case "explosionMassive": return .explosionMassive(duration: double(options, "duration", 1.8))
        case "shieldBlock": return .shieldBlock(duration: double(options, "duration", 0.35))
        case "criticalHit": return .criticalHit(duration: double(options, "duration", 0.5))
        case "comboHit3x": return .comboHit3x(duration: double(options, "duration", 0.8))
        case "comboHit5x": return .comboHit5x(duration: double(options, "duration", 1.2))
        case "footstepGrass": return .footstepGrass(duration: double(options, "duration", 0.2))
        case "footstepMetal": return .footstepMetal(duration: double(options, "duration", 0.2))
        case "engineStart": return .engineStart(duration: double(options, "duration", 2.0))
        case "turboBoost": return .turboBoost(duration: double(options, "duration", 1.5))
        case "portalEnter": return .portalEnter(duration: double(options, "duration", 0.8))
        case "magicCharge": return .magicCharge(duration: double(options, "duration", 1.0))
        case "machineGun": return .machineGun(duration: double(options, "duration", 2.0))
        case "cascade": return .cascade(duration: double(options, "duration", 0.8))
        case "elasticBounce": return .elasticBounce(duration: double(options, "duration", 2.0))
        case "drums": return .drums
        case "achievementUnlocked": return .achievementUnlocked(duration: double(options, "duration", 1.2))
        case "levelUp": return .levelUp(duration: double(options, "duration", 1.5))
        case "starRating": return .starRating(count: int(options, "count", 3), duration: double(options, "duration", 0.2))
        case "badgeEarned": return .badgeEarned(duration: double(options, "duration", 0.8))
        case "streakMilestone": return .streakMilestone(duration: double(options, "duration", 1.0))
        case "perfectScore": return .perfectScore(duration: double(options, "duration", 1.0))
        case "rankPromotion": return .rankPromotion(duration: double(options, "duration", 1.5))
        case "dailyGoalComplete": return .dailyGoalComplete(duration: double(options, "duration", 1.0))
        case "trophyUnlock": return .trophyUnlock(duration: double(options, "duration", 1.8))
        case "questComplete": return .questComplete(duration: double(options, "duration", 1.5))
        case "highScore": return .highScore(duration: double(options, "duration", 1.5))
        case "masteryAchieved": return .masteryAchieved(duration: double(options, "duration", 2.0))
        case "correctAnswerBasic": return .correctAnswerBasic(duration: double(options, "duration", 0.2))
        case "correctAnswerSimple": return .correctAnswerSimple(duration: double(options, "duration", 0.25))
        case "correctAnswerStreak": return .correctAnswerStreak(streakCount: int(options, "streakCount", 3), duration: double(options, "duration", 0.5))
        case "correctAnswerPerfect": return .correctAnswerPerfect(duration: double(options, "duration", 0.8))
        case "perfectLessonComplete": return .perfectLessonComplete(duration: double(options, "duration", 2.0))
        case "badgeUnlock": return .badgeUnlock(duration: double(options, "duration", 0.8))
        case "skillMastery": return .skillMastery(duration: double(options, "duration", 1.5))
        case "leaguePromotion": return .leaguePromotion(duration: double(options, "duration", 1.5))
        case "celebrationBurst": return .celebrationBurst(duration: double(options, "duration", 1.0))
        case "ascendingSuccess": return .ascendingSuccess(duration: double(options, "duration", 0.6))
        case "correctAnswer": return .correctAnswer(duration: double(options, "duration", 0.3))
        case "incorrectGentle": return .incorrectGentle(duration: double(options, "duration", 0.4))
        case "hintAvailable": return .hintAvailable(duration: double(options, "duration", 0.5))
        case "progressCheckpoint": return .progressCheckpoint(duration: double(options, "duration", 0.6))
        case "encouragementTap": return .encouragementTap(duration: double(options, "duration", 0.3))
        case "skillUnlocked": return .skillUnlocked(duration: double(options, "duration", 0.8))
        case "lessonComplete": return .lessonComplete(duration: double(options, "duration", 1.0))
        case "practiceReminder": return .practiceReminder(duration: double(options, "duration", 0.5))
        case "knowledgeGained": return .knowledgeGained(duration: double(options, "duration", 0.7))
        case "feedbackPositive": return .feedbackPositive(duration: double(options, "duration", 0.4))
        case "wrongAnswerGentle": return .wrongAnswerGentle(duration: double(options, "duration", 0.5))
        case "wrongAnswerStandard": return .wrongAnswerStandard(duration: double(options, "duration", 0.3))
        case "nearMissAnswer": return .nearMissAnswer(duration: double(options, "duration", 0.35))
        case "grammarError": return .grammarError(duration: double(options, "duration", 0.25))
        case "hintActivation": return .hintActivation(duration: double(options, "duration", 0.3))
        case "hintReveal": return .hintReveal(duration: double(options, "duration", 0.3))
        case "timeCriticalWarning": return .timeCriticalWarning(duration: double(options, "duration", 0.8))
        case "partialCredit": return .partialCredit(duration: double(options, "duration", 0.4))
        case "tryAgainEncouragement": return .tryAgainEncouragement(duration: double(options, "duration", 0.3))
        case "learningProgress": return .learningProgress(duration: double(options, "duration", 0.5))
        case "educationalFocusReminder": return .educationalFocusReminder(duration: double(options, "duration", 0.3))
        case "flashcardFlip": return .flashcardFlip(duration: double(options, "duration", 0.2))
        case "quizStart": return .quizStart(duration: double(options, "duration", 1.0))
        case "xpGainSmall": return .xpGainSmall(duration: double(options, "duration", 0.3))
        case "xpGainLarge": return .xpGainLarge(duration: double(options, "duration", 1.0))
        case "xpGainBonus": return .xpGainBonus(duration: double(options, "duration", 0.5))
        case "xpGainDynamic": return .xpGainDynamic(xpAmount: int(options, "xpAmount", 10), duration: double(options, "duration", 0.3))
        case "bonusPoints": return .bonusPoints(duration: double(options, "duration", 0.7))
        case "powerUpCollected": return .powerUpCollected(duration: double(options, "duration", 0.5))
        case "lifeGained": return .lifeGained(duration: double(options, "duration", 0.6))
        case "challengeAccepted": return .challengeAccepted(duration: double(options, "duration", 0.5))
        case "timerTick": return .timerTick(duration: double(options, "duration", 0.1))
        case "rewardUnlock": return .rewardUnlock(duration: double(options, "duration", 1.0))
        case "progressBarFill": return .progressBarFill(duration: double(options, "duration", 0.8))
        case "progressBarFilling": return .progressBarFilling(startPercent: double(options, "startPercent", 0.0), endPercent: double(options, "endPercent", 1.0), duration: double(options, "duration", 1.0))
        case "progress25": return .progress25(duration: double(options, "duration", 0.2))
        case "progress50": return .progress50(duration: double(options, "duration", 0.3))
        case "progress75": return .progress75(duration: double(options, "duration", 0.4))
        case "dailyGoalCheckpoint": return .dailyGoalCheckpoint(checkpointNumber: int(options, "checkpointNumber", 3), duration: double(options, "duration", 0.5))
        case "leagueAdvancement": return .leagueAdvancement(duration: double(options, "duration", 1.2))
        case "crownGemCollection": return .crownGemCollection(duration: double(options, "duration", 0.6))
        case "powerUpActivation": return .powerUpActivation(powerUpType: string(options, "powerUpType", "default"), duration: double(options, "duration", 0.5))
        case "challengeCompletion": return .challengeCompletion(isPerfect: bool(options, "isPerfect", false), duration: double(options, "duration", 1.0))
        case "lessonPathProgress": return .lessonPathProgress(nodeType: string(options, "nodeType", "default"), duration: double(options, "duration", 0.4))
        case "socialFeatureNotification": return .socialFeatureNotification(notificationType: string(options, "notificationType", "default"), duration: double(options, "duration", 0.6))
        case "comboMultiplier": return .comboMultiplier(count: int(options, "count", 3), duration: double(options, "duration", 0.6))
        case "streakRiskWarning": return .streakRiskWarning(duration: double(options, "duration", 0.6))
        case "streakLost": return .streakLost(duration: double(options, "duration", 0.5))
        case "streakBuilding": return .streakBuilding(streakCount: int(options, "streakCount", 3), duration: double(options, "duration", 0.5))
        case "streakMilestone5": return .streakMilestone5(duration: double(options, "duration", 0.6))
        case "streakMilestone7Days": return .streakMilestone7Days(duration: double(options, "duration", 1.0))
        case "streakMilestone10": return .streakMilestone10(duration: double(options, "duration", 0.8))
        case "streakMilestone25": return .streakMilestone25(duration: double(options, "duration", 1.2))
        case "streakMilestone30Days": return .streakMilestone30Days(duration: double(options, "duration", 1.5))
        case "streakMilestone100Days": return .streakMilestone100Days(duration: double(options, "duration", 2.0))
        case "doubleTapLike": return .doubleTapLike(duration: double(options, "duration", 0.2))
        case "messageSent": return .messageSent(duration: double(options, "duration", 0.25))
        case "notificationPop": return .notificationPop(duration: double(options, "duration", 0.3))
        case "typingIndicator": return .typingIndicator(duration: double(options, "duration", 0.1))
        case "commentPosted": return .commentPosted(duration: double(options, "duration", 0.2))
        case "pullToRefresh": return .pullToRefresh(duration: double(options, "duration", 0.4))
        case "swipeAction": return .swipeAction(duration: double(options, "duration", 0.25), actionType: string(options, "actionType", "default"))
        case "toggleSwitch": return .toggleSwitch(duration: double(options, "duration", 0.2))
        case "pickerDetent": return .pickerDetent(duration: double(options, "duration", 0.1))
        case "longPressActivation": return .longPressActivation(duration: double(options, "duration", 0.4))
        case "tabSelection": return .tabSelection(duration: double(options, "duration", 0.15))
        case "navigationPush": return .navigationPush(duration: double(options, "duration", 0.25))
        case "navigationPop": return .navigationPop(duration: double(options, "duration", 0.2))
        case "modalPresent": return .modalPresent(duration: double(options, "duration", 0.3))
        case "modalDismiss": return .modalDismiss(duration: double(options, "duration", 0.25))
        case "keyboardTap": return .keyboardTap(duration: double(options, "duration", 0.05))
        case "sliderStep": return .sliderStep(duration: double(options, "duration", 0.05))
        case "sliderTick": return .sliderTick(duration: double(options, "duration", 0.05))
        case "buttonPress": return .buttonPress(duration: double(options, "duration", 0.03))
        case "selectionTick": return .selectionTick(duration: double(options, "duration", 0.1))
        case "segmentChange": return .segmentChange(duration: double(options, "duration", 0.15))
        case "zoomBoundary": return .zoomBoundary(duration: double(options, "duration", 0.2))
        case "dragAndDrop": return .dragAndDrop(duration: double(options, "duration", 0.25), phase: string(options, "phase", "start"))
        case "formSubmit": return .formSubmit(duration: double(options, "duration", 0.3))
        case "inputError": return .inputError(duration: double(options, "duration", 0.4))
        case "loadingComplete": return .loadingComplete(duration: double(options, "duration", 0.5))
        case "appIconTap": return .appIconTap(duration: double(options, "duration", 0.15))
        case "scrollBounce": return .scrollBounce(duration: double(options, "duration", 0.3))
        case "pageFlip": return .pageFlip(duration: double(options, "duration", 0.3))
        case "photoCapture": return .photoCapture(duration: double(options, "duration", 0.2))
        case "shareAction": return .shareAction(duration: double(options, "duration", 0.3))
        case "downloadComplete": return .downloadComplete(duration: double(options, "duration", 0.5))
        case "refreshData": return .refreshData(duration: double(options, "duration", 0.4))
        case "gestureRecognized": return .gestureRecognized(duration: double(options, "duration", 0.2))
        case "pageTurn": return .pageTurn(duration: double(options, "duration", 0.3))
        case "bookPageTurn": return .bookPageTurn(duration: double(options, "duration", 0.25))
        case "softTick": return .softTick(duration: double(options, "duration", 0.3))
        case "customPop": return .customPop(duration: double(options, "duration", 0.15))
        case "contextualMenu": return .contextualMenu(duration: double(options, "duration", 0.25))
        case "sliderValueChange": return .sliderValueChange(duration: double(options, "duration", 0.06))
        case "pop": return .pop(duration: double(options, "duration", 0.2))
        case "magicSparkle": return .magicSparkle(duration: double(options, "duration", 1.2))
        case "waterDrop": return .waterDrop(duration: double(options, "duration", 0.6))
        case "specialEarthquake": return .specialEarthquake(duration: double(options, "duration", 2.5))
        case "laserBeam": return .laserBeam(duration: double(options, "duration", 0.8))
        case "typewriter": return .typewriter(duration: double(options, "duration", 0.04))
        case "heartbeat": return .heartbeat(duration: double(options, "duration", 1.5))
        case "electricSpark": return .electricSpark(duration: double(options, "duration", 0.3))
        case "rubberBand": return .rubberBand(duration: double(options, "duration", 0.4))
        case "buildUp": return .buildUp(duration: double(options, "duration", 2.0))
        case "boing": return .boing(duration: double(options, "duration", 0.25))
        case "inflate": return .inflate(duration: double(options, "duration", 1.7))
        case "oscillate": return .oscillate(duration: double(options, "duration", 3.0))
        case "breathingGuide": return .breathingGuide(duration: double(options, "duration", 4.0))
        case "calmPulse": return .calmPulse(duration: double(options, "duration", 2.0))
        case "meditationBell": return .meditationBell(duration: double(options, "duration", 1.5))
        case "relaxationWave": return .relaxationWave(duration: double(options, "duration", 3.0))
        case "zenNotification": return .zenNotification(duration: double(options, "duration", 1.2))
        case "timeWarning30s": return .timeWarning30s(duration: double(options, "duration", 0.5))
        case "timeWarning10s": return .timeWarning10s(duration: double(options, "duration", 0.8))
        case "heartBeats": return .heartBeats(count: int(options, "count", 3), durationPerBeat: double(options, "durationPerBeat", 0.255))
        case "timerComplete": return .timerComplete(duration: double(options, "duration", 1.5))
        case "taskCheck": return .taskCheck(duration: double(options, "duration", 0.2))
        case "focusStart": return .focusStart(duration: double(options, "duration", 0.8))
        case "breakReminder": return .breakReminder(duration: double(options, "duration", 1.2))
        case "productivityFocusReminder": return .productivityFocusReminder(duration: double(options, "duration", 0.25))
        case "paymentSuccess": return .paymentSuccess(duration: double(options, "duration", 0.1))
        case "paymentProcessing": return .paymentProcessing(duration: double(options, "duration", 2.0))
        case "transactionAlert": return .transactionAlert(duration: double(options, "duration", 0.5))
        case "receiptSaved": return .receiptSaved(duration: double(options, "duration", 0.4))
        case "excitementBuild": return .excitementBuild(duration: double(options, "duration", 2.0))
        case "disappointment": return .disappointment(duration: double(options, "duration", 0.8))
        case "surprise": return .surprise(duration: double(options, "duration", 0.5))
        case "joy": return .joy(duration: double(options, "duration", 1.2))
        case "anticipation": return .anticipation(duration: double(options, "duration", 2.0))
        case "fireBurst": return .fireBurst(duration: double(options, "duration", 1.0))
        case "iceShard": return .iceShard(duration: double(options, "duration", 1.5))
        case "earthquakeRumble": return .earthquakeRumble(duration: double(options, "duration", 2.5))
        case "windTornado": return .windTornado(duration: double(options, "duration", 1.8))
        case "thunderStorm": return .thunderStorm(duration: double(options, "duration", 2.5))
        case "meteorImpact": return .meteorImpact(duration: double(options, "duration", 3.0))
        case "intenseEarthquake": return .intenseEarthquake(duration: double(options, "duration", 2.5))
        case "intenseTornado": return .intenseTornado(duration: double(options, "duration", 1.8))
        case "plasmaCharge": return .plasmaCharge(duration: double(options, "duration", 1.5))
        case "gravityWell": return .gravityWell(duration: double(options, "duration", 2.0))
        case "photonBlast": return .photonBlast(duration: double(options, "duration", 0.8))
        case "quantumShift": return .quantumShift(duration: double(options, "duration", 0.6))
        case "rocketLaunch": return .rocketLaunch(duration: double(options, "duration", 3.0))
        case "warpDrive": return .warpDrive(duration: double(options, "duration", 2.0))
        case "laserCannon": return .laserCannon(duration: double(options, "duration", 0.5))
        case "alienTeleport": return .alienTeleport(duration: double(options, "duration", 1.0))
        case "spaceExplosion": return .spaceExplosion(duration: double(options, "duration", 2.5))
        case "ultimatePower": return .ultimatePower(duration: double(options, "duration", 3.0))
        case "dragonRoar": return .dragonRoar(duration: double(options, "duration", 2.0))
        case "titanSmash": return .titanSmash(duration: double(options, "duration", 1.5))
        case "dimensionalRift": return .dimensionalRift(duration: double(options, "duration", 2.5))
        case "volcanicEruption": return .volcanicEruption(duration: double(options, "duration", 3.5))
        case "titanStomp": return .titanStomp(duration: double(options, "duration", 1.5))
        case "phoenixRebirth": return .phoenixRebirth(duration: double(options, "duration", 2.0))
        case "divineIntervention": return .divineIntervention(duration: double(options, "duration", 2.5))
        case "megaBoost": return .megaBoost(duration: double(options, "duration", 1.5))
        case "starPower": return .starPower(duration: double(options, "duration", 2.0))
        case "berserkerRage": return .berserkerRage(duration: double(options, "duration", 2.0))
        case "divineShield": return .divineShield(duration: double(options, "duration", 1.5))
        case "invincibilityActivation": return .invincibilityActivation(duration: double(options, "duration", 2.0))
        case "timeFreeze": return .timeFreeze(duration: double(options, "duration", 2.5))
        case "ultraCombo": return .ultraCombo(duration: double(options, "duration", 3.0))
        case "nuclearCharge": return .nuclearCharge(duration: double(options, "duration", 2.5))
        case "starRating1": return .starRating1(duration: double(options, "duration", 0.1))
        case "starRating3": return .starRating3(duration: double(options, "duration", 0.3))
        case "starRating5": return .starRating5(duration: double(options, "duration", 0.8))
        case "socialNotification": return .socialNotification(notificationType: string(options, "notificationType", "default"), duration: double(options, "duration", 0.4))
        case "pencilWrite": return .pencilWrite(duration: double(options, "duration", 0.05))
        case "eraserUse": return .eraserUse(duration: double(options, "duration", 0.2))
        default: return nil
        }
    }

    private static func double(_ options: [String: Any]?, _ key: String, _ defaultValue: Double) -> Double {
        if let value = options?[key] as? NSNumber { return value.doubleValue }
        if let value = options?[key] as? String, let parsed = Double(value) { return parsed }
        return defaultValue
    }

    private static func int(_ options: [String: Any]?, _ key: String, _ defaultValue: Int) -> Int {
        if let value = options?[key] as? NSNumber { return value.intValue }
        if let value = options?[key] as? String, let parsed = Int(value) { return parsed }
        return defaultValue
    }

    private static func string(_ options: [String: Any]?, _ key: String, _ defaultValue: String) -> String {
        if let value = options?[key] as? String { return value }
        return defaultValue
    }

    private static func bool(_ options: [String: Any]?, _ key: String, _ defaultValue: Bool) -> Bool {
        if let value = options?[key] as? NSNumber { return value.boolValue }
        if let value = options?[key] as? Bool { return value }
        if let value = options?[key] as? String { return (value as NSString).boolValue }
        return defaultValue
    }
}
